### ISSUE TITLE
CMS links disappear

### ISSUE THREAD

**Issue by dathwa** [vdlp/oc-sitemap-plugin#1]
Hi.
I've created my own generator for a small 'jobs' plugin. The links appear fine in the sitemap, but the CMS pages disappear. If I disable the sitemap for my plugin the CMS pages appear again.

My class...
```
namespace Acme\Jobs\Classes;

use Carbon\Carbon;
use Illuminate\Contracts\Routing\UrlGenerator;
use Psr\Log\LoggerInterface;
use Throwable;
use Vdlp\Sitemap\Classes\Contracts\DefinitionGenerator;
use Vdlp\Sitemap\Classes\Dto;

final class JobsPagesGenerator implements DefinitionGenerator
{
    public function getDefinitions(): Dto\Definitions
    {
        $definitions = new Dto\Definitions();
        for ($i = 0; $i < 10; $i++) {
            $definitions->addItem(
                (new Dto\Definition)->setModifiedAt(Carbon::now())
                    ->setPriority(1)
                    ->setUrl(url("jobs/".$i) )
                    ->setChangeFrequency(Dto\Definition::CHANGE_FREQUENCY_ALWAYS)
            );
        }

        return $definitions;
    }
}
```

Any help very much appreciated. Thank-you.

**Comment by adrenth** [comment]
To be clear:

- Are you using the https://github.com/vdlp/oc-sitemapgenerators-plugin?
- Which OC installation build are you running?

**Comment by dathwa** [comment]
Hi. I played about with the cache values and the situation has resolved its-self.

yes - i was using https://github.com/vdlp/oc-sitemapgenerators-plugin
OC v471

Thank-you.
